### ISSUE TITLE
Wiki in Chapter "Tutorial-3.-Simple-Bulk-Validation,-Multiple-Packages" is broken

### ISSUE THREAD

**Issue by Samuel3** [oshoukry/openpojo#103]
In only displays the following message 

> ``` Java PojoClassFactory.getPojoClassesRecursively(packageName, new FilterClassName("\\w*Test\\w*$")); ``` #### 3. FilterEnum This filter enables you to get all classes that are _not_ of type Enum. ``` Java PojoClassFactory.getPojoClassesRecursively(packageName, new FilterEnum()); ```

**Comment by oshoukry** [comment]
Thank you for the catch!
Fixed now.
