### ISSUE TITLE
Java 9 compatibility

### ISSUE THREAD

**Issue by JohnZavyn** [oshoukry/openpojo#108]
com.openpojo.reflection.java.packageloader.boot.JavaBootClassLoader is hard coded to pull the class path from System.getProperty("sun.boot.class.path"). However, this system property has been removed in Java 9, resulting in a null pointer exception.

In debug mode, I was able to manually replace this with "java.class.path", which appeared to work correctly.

See https://docs.oracle.com/javase/8/docs/technotes/tools/windows/findingclasses.html

I see this property is also available in Java 1.7 and 1.8, but I have not checked earlier versions.

For backwards compatibility, it might be useful to check "java.class.path" first, and then "sun.boot.class.path" if the former returns a null.

Love your product, and want to keep using it in Java 9! 😄

**Comment by JohnZavyn** [comment]
Also note that after getting the path, I get the following warnings:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.openpojo.reflection.impl.PojoFieldImpl (file:/Users/johnmarsh/.m2/repository/com/openpojo/openpojo/0.8.6/openpojo-0.8.6.jar) to field java.lang.Exception.serialVersionUID
WARNING: Please consider reporting this to the maintainers of com.openpojo.reflection.impl.PojoFieldImpl
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

I seem to remember reading that Oracle will be better protecting in the future, but I can't find my reference at the moment, and I don't recall if there will be other, preferred ways of doing reflection in the future...

Thanks again!

**Comment by JohnZavyn** [comment]
To work around this problem, I added the following to my JUnit test:

    /**
     * <p>Workaround to allow OpenPojo version 0.8.6 to work with Java 9.</p> 
     * <p>TODO: Remove when OpenPojo is updated</p>
     */
    @BeforeClass
    public static void setSystemProperty()
    {
        System.setProperty("sun.boot.class.path", System.getProperty("java.class.path"));
    }

**Comment by oshoukry** [comment]
So the main issue that this was opened on is now resolved which is the exception being thrown.
I'll open another issue for supporting Java 9.
