### ISSUE TITLE
Add possiblity to enable pojoValidator for testing enums

### ISSUE THREAD

**Issue by HenrikPilz** [oshoukry/openpojo#58]
I'd like to test a few Enums which are not only Enums, but implement some interfaces and have additional properties. They are enums because I can state all possible values in advance. but I have to check, whether someone changes something.

Could you add a switch for the PojoValidator to enable BehaviourTesting for enums?
Maybe something like, enableEnumTesting() or so?

Regards Henrik

**Comment by HenrikPilz** [comment]
Already did it with Rules. So issue closed. ;) Thanks.

**Comment by oshoukry** [comment]
Thank you Henrik for the feedback, I would be interested to know the nature of the tests you are doing on Enums.

**Comment by HenrikPilz** [comment]
I've got some MetaInfo Files which we designed as Enums with additional interfaces.
Due to the design of the whole software (hist(e/o)rically grown over 23 years) some fields/enum values have to come up in every Enum. Thus I would like to test, that the meta-information they are carrying is always the same. (because it's always the same field.)

Yes I know, that this is no good design, but unfortunately I do not have a choice at the moment.

Btw: Your Framework is really helpful for me!! Awesome work!

**Comment by oshoukry** [comment]
Thank you Henrik for your continued interest in OpenPojo, and I am glad it has been helpful to you.

Is it possible to attach a sample for the structure you are dealing with, and the tests / rules you'd like to see validated.

Coding up some rules / tests specifically for Enums should be quite straight forward and easy to do.

Thank you and have a wonderful weekend!
