### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jeffpeiyt** [oshoukry/openpojo#63]
Hi Osman,

We love your project and would like to use it in our to be open sourced software, however we have issues due to the LGPL
http://programmers.stackexchange.com/questions/136702/does-the-lgpl-allow-me-to-do-this

Is there any chance you may make OpenPojo license as Apache 2.0?

thanks,

Jeff

**Comment by davidkarlsen** [comment]
+1

**Comment by oshoukry** [comment]
With LGPL 3, if you modify OpenPojo's source then your work should be released under the same license. But contrary to GPL, programs linked against a library under the LGPL do not need to be released under the LGPL and can be kept proprietary. It must be linked dynamically, not statically as the user must keep the ability to update the library independently from the program.

Inheriting from a class or implementing an interface is dynamic linking and LGPL doesn't restrict this at all.

Please let me know if you have made specific changes that would prevent you from releasing under Apache 2.0, I'm happy to discuss changes to licensing.

__Resources:__
- http://www.cnx-software.com/2011/10/10/open-source-licenses-overview-gpl-lgpl-apache-bsd/
- https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License#Class_inheritance

**Comment by jeffpeiyt** [comment]
Thanks Osman for the kind reply and help. The LGPL has some grey areas and I will check with our legal on this and let you know if we need your further help.

**Comment by oshoukry** [comment]
Please let me know what your legal department responds with.
I have zero intention to have a licensing scheme that prevents other's ability to provide goodness especially with respect to the open source community.

**Comment by jeffpeiyt** [comment]
Hi Osman,

Thanks for the kind help. We just got feedback from our legal and our legal have concerns on the LGPL license and prefer it to change to Apache 2.  It is controversial and different people may interpret it differently so we cannot safely import it.  

Would be super nice if you could change it to Apache v2  / BSD / MIT  ( apache v2 is safe for sure). I am sure this will help other people to use it too and increase adoption. 

Looking forward to your help.

Thanks,

**Comment by jeffpeiyt** [comment]
Hi Osman,

we really would like to use your library and appreciate your help on this.... or we will have to manually testing all setter/getters  

:-)

**Comment by oshoukry** [comment]
I'll update the next version this weekend with an updated license.
Thank you for looking into it and getting legal advice.

**Comment by jeffpeiyt** [comment]
Thanks so much Osman!! We are looking forward to the next version.

Have a great one,

Jeff

**Comment by jeffpeiyt** [comment]
Hi Osman,

Would like to follow up with the request. We are counting on it. Looking forward to your help :-)

Thanks,

Jeff

**Comment by oshoukry** [comment]
Release OpenPojo-0.8.0 is now out and is licensed under Apache 2.0.

Thank you for your continued interest and support of OpenPojo.

Happy Testing & Identity Management!!

**Comment by jeffpeiyt** [comment]
Thanks so much Osman! This is awesome! We will put a thank you when we open source the project on your effort.

**Comment by jeffpeiyt** [comment]
Osman, thanks again in the help. We open sourced the Parallec and mentioned you as the credit!

https://github.com/eBay/parallec#authors

Thanks!

**Comment by oshoukry** [comment]
Thank you so much, Parallec looks quite interesting, best of luck.
