### ISSUE TITLE
No way to turn off Debug logging

### ISSUE THREAD

**Issue by ohiocowboy** [oshoukry/openpojo#64]
I have a fairly large amount of classes I'm testing. With several hundreds of debug statements being printed. I would like to see the ability to turn off the debug statements so that unnecessary log statements are printed.

Thanks,

**Comment by oshoukry** [comment]
OpenPojo does have quite a few debug statements, but they will all come out under the com.openpojo hierarchy, so it depends wether you are using SLF4J or Log4J how you configure and set a different log level for com.openpojo log appender.

For example, if you are using Log4J 1.2.x and using properties files adding this line:
log4j.logger.com.openpojo=OFF

Will shutoff all output from OpenPojo, you may also set it to DEBUG, INFO, WARN, ERROR, FATAL or OFF.

If you are using Log4J 2.x over xml configuration, you'll need to add
<Logger name="com.openpojo" level="off">
</Logger>

See your specific logging provider for details, OpenPojo will attempt to detect and send its logs based on auto-detecting the logging framework provided, starting from SLF4J, falling back to Log4J, and finally over to JavaLogger.

Hope this helps.

- Osman

**Comment by mrkk** [comment]
springboot uses slf4j and logback, and its definitely not respecting my logback settings
