### ISSUE TITLE
Gradle - Eclipse - Test classes exclusion

### ISSUE THREAD

**Issue by Gusa86** [oshoukry/openpojo#76]
Hello:
I am using Gradle to create an Eclipse project. It creates two folders one called src/main/java y andother called src/test/java however it creates two packages called the same way lets call test.model. When I try to define :
private static final String POJO_PACKAGE = "test.model";

It finds the classes tha are in test and main folder, not only in main folder. That is to say it search inside the text package inside the test folder. I think because it has the same name. They must have the same name, the test and the src package. 

So the question is : How can I exclude the test package without renaming it?

I have seen that it is possible to create a filter including files with regex however I can´t exclude test files.

**Comment by oshoukry** [comment]
Not sure where Gradle stores the test classes, take a look at https://github.com/oshoukry/openpojo/wiki/Tutorial-8.-Testing-Only-Production-classes and let me know if that helps.

**Comment by oshoukry** [comment]
I haven't heard back on this, can you please confirm that the suggested tutorial infact fixed the issue?
Happy to help if you're still having problems with this, otherwise, closing the issue.
