### ISSUE TITLE
Add getGetter(), getSetter(), and getField() to PojoField

### ISSUE THREAD

**Issue by drdamour** [oshoukry/openpojo#79]
I have tests that want to verify things based on the the presence of annotations on the getter.  There's no good way for me to get the PojoField's PojoMethod for the setter.

Suggest opening up this class a bit to expose the already contained getter, setter methods, as well as the  java.lang.reflect.Field type for more advanced things.

**Comment by oshoukry** [comment]
Release 0.8.4 is out, please update and let me know if there are any other issues you are experiencing.
Thank you for your support and interest in OpenPojo.

**Comment by drdamour** [comment]
works great!  thanks
