### ISSUE TITLE
Inheritence support in getPojoFields or another method

### ISSUE THREAD

**Issue by drdamour** [oshoukry/openpojo#80]
I was surprised getPojoFields didn't return inherited fields.  I've been using this helper method to get all fields, even those inherited.

```
public static Map<PojoField, PojoClass> getAllFieldsIncludingInherited(PojoClass pojoClass){
        Map<PojoField, PojoClass> fields = new HashMap<PojoField, PojoClass>();

        PojoClass c = pojoClass;

        while(c != null){
            for(PojoField field : c.getPojoFields()){
                fields.put(field, c);
            }

            c = c.getSuperClass();
        }

        return fields;
    }
```

The map is because i need the PojoClass to getClazz().getDeclaredField(PojoField.getName()) in order to get a handle to the getters and setters method (using method factory).  This wouldn't be necessary if #79 was implemented.

**Comment by oshoukry** [comment]
Closing issue as issue #79 has already been implemented.
Please feel free to update if further assistance on this is required.

**Comment by drdamour** [comment]
all that 79 doe it make reflection not necessary...there still needs to be a way to get all inherited fields with getPojoFields in my opinion...can you please reopen?

**Comment by oshoukry** [comment]
Thank you for your timely response, I'll open an issue specifically to get all inherited fields as a separate enhancement as this issue mentions that #79 makes it not necessary.

**Comment by drdamour** [comment]
it makes returning a map not necessary..the issue is still the issue

**Comment by oshoukry** [comment]
See issue #101 please feel free to comment on that regarding enhancing the PojoClass to get all fields.
