### ISSUE TITLE
Make Validator more usable.

### ISSUE THREAD

**Issue by oshoukry** [oshoukry/openpojo#86]
With the move from PojoValidator to Validator interface, while the boiler plate code became a lot less, a critical piece of information was also lost.

There is no way to know currently what the Validator has enumerated and operated on / verified.
Returning a List<PojoClass> would remedy that so extra asserts can be placed for the count of Pojo's enumerated, and which ones they were.

**Comment by rotilho** [comment]
Could you provide an example how it was working before with PojoValidator?

**Comment by oshoukry** [comment]
With previous PojoValidator you enumerated the List<PojoClass> to be validated, so you knew what would be tested, but with the current Validator you have the ability to pass in a package name and a set of filters to run though, this works, but you have no way of knowing which classes were tested.

**Comment by rotilho** [comment]
Something like validator.validate(listOfPojos)?

If yes the Validator has this possibility but there is not fancy way to collect the listOfPojos. In this case take a look in my PR #87

**Comment by oshoukry** [comment]
Thank you for your contribution, but I've made a change more in line with what I wanted to see from Validator to enable someone to inspect and ensure the Pojos validated are the ones expected.
