### ISSUE TITLE
Static fields are being polluted.

### ISSUE THREAD

**Issue by Otanikotani** [oshoukry/openpojo#99]
```java
public class PojoWithStaticFieldTest {

    @After
    public void checkStaticFieldValue() {
        System.out.println(Foo.i);
    }

    @Test
    public void test_static_field() throws Exception {
        Validator validator = ValidatorBuilder.create().with(new GetterTester()).build();

        validator.validate(PojoClassFactory.getPojoClass(Foo.class));
    }

    static class Foo {
        static int i;

        public static int getI() {
            return i;
        }
    }
}
```

Here is the JUnit test using OpenPojo's GetterTester to test the field `i` in class Foo. The problem is that after the test the value remains the same as it was set by OpenPojo even though the field is static. This might cause different problems and an unexpected test execution if some other tests rely on these static values. Let's testA is an OpenPojo test which modifies the static variable and testB uses the static value as well. Then if tests are run in parallel there are no guarantees. 

Possible solutions:
- Filter out static fields when building `PojoClass`. 
- Restore  the previous value set in static field after the test. This might still cause problems for parallel test execution. 

Our solution was to write a decorator and wrap `GetterTester` filtering out static pojo fields before actually executing the `GetterTester`.

**Comment by oshoukry** [comment]
This is an interesting corner case, what is the reason you have a static non-final that carries critical info during testing?  How do you deal with multithreading issues during production executions of the code?

**Comment by Otanikotani** [comment]
Oh well, it is a legacy system and my current target is to increase the coverage of the code base for making refactoring more bullet-proof. So, since it is legacy code it contains such non-final fields, I believe in my case it is some very weird implementation of Singleton with ```setInstance()``` which is probably called only once during program's startup.

**Comment by oshoukry** [comment]
Thank you for your feedback.
I recommend in this case, perhaps its best to write a custom one off Tester / Rule for this particular case, and filter this one class out of all your other tests.  Not sure generalizing this in the core code of OpenPojo would encourage the right practices.  Please let me know if you need help driving that code, happy to supply a sample on this issue.

**Comment by Otanikotani** [comment]
Okay, thank you. I did something like this before, so I hope it is going to be easy, no help needed. Thank you for offering, though.

**Comment by oshoukry** [comment]
Closing issue, please feel free to re-open if additional feedback is necessary.
